class nagiosopenstack::config (
  $nagios_server = undef,
  $nagios_user = 'nagiosadmin',
  $nagios_password = 'nagiosAdmin',
  $openstack_router_list = [],
  $openstack_network_list = [],
  $openstack_tenant_list = [],
  $openstack_controller_service_list = [],
  $openstack_compute_service_list = [],
  $openstack_neutron_service_list = [],
  $openstack_cinder_service_list = [],
  $openstack_glance_service_list = [],
  $openstack_auth_url = undef,
  $openstack_neutron_url = undef,
  $openstack_nova_url = undef,
  $openstack_glance_url = undef,
  $openstack_cinder_url = undef,
  $openstack_username = undef,
  $openstack_password = undef,
  $openstack_tenant = undef,
  $openstack_openvswitch_external_bridge = undef,
) {
}
